//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produs()
        {
            this.Comanda = new HashSet<Comanda>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public string Ingrediente { get; set; }
        public decimal Pret { get; set; }
        public decimal EnergieCalorica { get; set; }
        public decimal Proteine { get; set; }
        public decimal Carbohidrati { get; set; }
        public string Poza { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda> Comanda { get; set; }
    }
}
