//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipProdus
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
        public string Ingrediente { get; set; }
        public decimal Pret { get; set; }
        public decimal EnergieCalorica { get; set; }
        public decimal Proteine { get; set; }
        public decimal Carbohidrati { get; set; }
    }
}
